export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_RESET = "CART_RESET";

export const GET_SUGGEST_REQUEST = "GET_SUGGEST_REQUEST";
export const GET_SUGGEST_SUCCESS = "GET_SUGGEST_SUCCESS";
export const GET_SUGGEST_FAIL = "GET_SUGGEST_FAIL";