export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_RESET = "CART_RESET";

export const GET_TOP_PRODUCTS_REQUEST = "GET_TOP_PRODUCTS_REQUEST";
export const GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS";
export const GET_TOP_PRODUCTS_FAIL = "GET_TOP_PRODUCTS_FAIL";

export const GET_DEPARTMENTS_PIE_REQUEST = "GET_DEPARTMENTS_PIE_REQUEST";
export const GET_DEPARTMENTS_PIE_SUCCESS = "GET_DEPARTMENTS_PIE_SUCCESS";
export const GET_DEPARTMENTS_PIE_FAIL = "GET_DEPARTMENTS_PIE_FAIL";